baseurl = "/"
title = "endeavouRs"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "R and shiny based data analysis and projects"
  copyright = "&copy;2017 David Earl"
  sidebarAbout = [
    "I am a scientist and tinkerer currently based in Nashville"
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [params.social]
  email         = "davidcearl@gmail.com"
  linkedin      = "full profile url in linkedin"
  github        = "https://github.com/davidcearl/"
